const content = {
  en: {
    lang: 'en', title: 'What deserves to be accelerated?', subtitle: 'Structural Thesis & Decision Architecture', proposal: 'Proposal for accelerators & ventures', scale: 'What deserves<br>to be <em>accelerated?</em>', lead: 'Before scaling execution, determine what deserves to scale.', role: 'Structural Thesis Advisor', founder: 'Founder, Kernel Institute', nav: ['Opening','Irreversibility','Trajectory','Scale','Delegation','Build','Contribution','Closing'], slides: [
      ['01 / Before irreversibility','A hypothesis<br>can become <em>infrastructure.</em>','The better the execution, the faster a wrong premise becomes expensive, complex and difficult to remove.',['Premise|An assertion about the world begins to support the business.','Commitment|Product, process and capital begin to depend on it.','Infrastructure|Automation and operations make the premise difficult to revise.'],'What must be true for this company to work?'],
      ['02 / A trajectory','Three questions.<br><em>One contribution.</em>','',['Should it scale?|Does the structural thesis deserve to scale?','What can be delegated?|What can be delegated while preserving independence, evidence and accountability?','How should it be built?|How do we turn the thesis into executable architecture?'],''],
      ['03 / Should it scale?','Separate structure<br>from <em>narrative.</em>','Make the fundamental assertion supporting the business explicit.',['Observed evidence|Hypothesis|Contextual dependency|Convention|Design choice','Q Stop Criterion|A criterion before premises become capital, software, automation or infrastructure.','Q for Venture|Investigate the startup thesis and distinguish structural insight from narrative strength.'],'Is there enough structural evidence to allow this premise to scale?'],
      ['04 / What can be delegated?','Ability to execute.<br><em>Legitimacy to decide.</em>','Should the system occupy this function? Can it verify its own execution? Can it control the record used to prove it? Can it judge conflicts in which it participates?',['Execution, evidence and adjudication must be separated.','Functions with conflicts of interest must remain independent.','Provenance, temporal reconstruction and accountability are required.'],'Research: Impossible Delegation · Universal Verification Principle · The Blind Algorithm · Algorithmic Verifiability'],
      ['05 / How should it be built?','From thesis to<br><em>executable system.</em>','Nearly three decades in technology and regulated environments, connected to a line of applied research.',['Entity360|Entities, roles, relationships, conditions, states and time.','MS360|Organizational memory, provenance and decision reconstruction.','QuipuDB / QuipuKM|Architectures for data, semantics, temporality and knowledge.'],'Use implementation to test what research claims.'],
      ['06 / Contribution to acceleration','A capability for<br><em>the accelerator itself.</em>','',['Before|Examine the thesis|Structural Thesis Review for complex opportunities.','During|Structure with the founder|Separate hypothesis, architecture, delegation and implementation.','At scale|Review the commitment|Introduce a stop criterion before premises enter infrastructure.'],'AI & Agentic Systems|Deep Tech|HealthTech|LegalTech / RegTech|GovTech|Research-to-Product'],
      ['Structural Thesis Advisor','Before building it<br>the right way,<br><em>determine whether it is<br>the right thing to build.</em>','',['Benjamin Rivera Perez|Founder, Kernel Institute|Founder & CEO, Hyperweb Healthtech OÜ|Technology Executive & Systems Architect, Megaweb Solutions'],'kernel.institute']
    ]
  },
  pt: {
    lang: 'pt-BR', title: 'O que merece ser acelerado?', subtitle: 'Tese Estrutural e Arquitetura de Decisão', proposal: 'Proposta para aceleradoras e ventures', scale: 'O que, exatamente,<br>merece ser <em>escalado?</em>', lead: 'Antes de escalar a execução, determine o que merece escalar.', role: 'Consultor de Tese Estrutural', founder: 'Fundador, Kernel Institute', nav: ['Abertura','Irreversibilidade','Trajetória','Escala','Delegação','Construção','Contribuição','Encerramento'], slides: [
      ['01 / Antes da irreversibilidade','Uma hipótese<br>pode virar <em>infraestrutura.</em>','Quanto melhor a execução, mais rápido uma premissa equivocada se torna cara, complexa e difícil de remover.',['Premissa|Uma afirmação sobre o mundo começa a sustentar o negócio.','Compromisso|Produto, processos e capital passam a depender dela.','Infraestrutura|Automação e operação tornam essa premissa difícil de revisar.'],'O que precisa ser verdade para esta empresa funcionar?'],
      ['02 / Uma trajetória','Três perguntas.<br><em>Uma contribuição.</em>','',['Deve escalar?|A tese estrutural merece escalar?','O que pode ser delegado?|O que pode ser delegado preservando independência, prova e responsabilidade?','Como deve ser construído?|Como transformar a tese em arquitetura executável?'],''],
      ['03 / Deve escalar?','Separar estrutura<br>de <em>narrativa.</em>','Tornar explícita a afirmação fundamental que sustenta o negócio.',['Evidência observada|Hipótese|Dependência contextual|Convenção|Escolha de design','Q Stop Criterion|Um critério antes que premissas se tornem capital, software, automação ou infraestrutura.','Q for Venture|Investigar a tese da startup e distinguir structural insight de narrative strength.'],'Há evidência estrutural suficiente para permitir que esta premissa escale?'],
      ['04 / O que pode ser delegado?','Capacidade de executar.<br><em>Legitimidade para decidir.</em>','O sistema deve ocupar esta função? Pode verificar a própria execução? Pode controlar o registro usado para prová-la? Pode julgar conflitos dos quais participa?',['Separação entre execução, prova e adjudicação.','Independência de funções com conflito de interesse.','Proveniência, reconstrução temporal e accountability.'],'Pesquisa: Impossible Delegation · Universal Verification Principle · The Blind Algorithm · Algorithmic Verifiability'],
      ['05 / Como deve ser construído?','Da tese ao<br><em>sistema executável.</em>','Quase três décadas em tecnologia e ambientes regulados, conectadas a uma linha própria de pesquisa aplicada.',['Entity360|Entidades, papéis, relações, condições, estados e tempo.','MS360|Memória organizacional, proveniência e reconstrução de decisões.','QuipuDB / QuipuKM|Arquiteturas para dados, semântica, temporalidade e conhecimento.'],'Usar implementação para testar aquilo que a pesquisa afirma.'],
      ['06 / Contribuição à aceleração','Uma capacidade para<br><em>a própria aceleradora.</em>','',['Antes|Examinar a tese|Structural Thesis Review em oportunidades de maior complexidade.','Durante|Estruturar com o founder|Separar hipótese, arquitetura, delegação e implementação.','Na escala|Revisar o compromisso|Introduzir um stop criterion antes de incorporar premissas à infraestrutura.'],'AI & Agentic Systems|Deep Tech|HealthTech|LegalTech / RegTech|GovTech|Research-to-Product'],
      ['Consultoria de Tese Estrutural','Antes de construir<br>da forma correta,<br><em>determine se é<br>a coisa certa a construir.</em>','',['Benjamin Rivera Perez|Fundador, Kernel Institute|Fundador e CEO, Hyperweb Healthtech OÜ|Executivo de Tecnologia e Arquiteto de Sistemas, Megaweb Solutions'],'kernel.institute']
    ]
  },
  es: {
    lang: 'es', title: '¿Qué merece ser acelerado?', subtitle: 'Tesis Estructural y Arquitectura de Decisión', proposal: 'Propuesta para aceleradoras y ventures', scale: '¿Qué, exactamente,<br>merece ser <em>escalado?</em>', lead: 'Antes de escalar la ejecución, determine qué merece escalar.', role: 'Asesor de Tesis Estructural', founder: 'Fundador, Kernel Institute', nav: ['Inicio','Irreversibilidad','Trayectoria','Escala','Delegación','Construcción','Contribución','Cierre'], slides: [
      ['01 / Antes de la irreversibilidad','Una hipótesis<br>puede convertirse en <em>infraestructura.</em>','Cuanto mejor la ejecución, más rápido una premisa equivocada se vuelve costosa, compleja y difícil de eliminar.',['Premisa|Una afirmación sobre el mundo empieza a sostener el negocio.','Compromiso|Producto, procesos y capital comienzan a depender de ella.','Infraestructura|La automatización y la operación hacen difícil revisar la premisa.'],'¿Qué debe ser verdad para que esta empresa funcione?'],
      ['02 / Una trayectoria','Tres preguntas.<br><em>Una contribución.</em>','',['¿Debe escalar?|¿La tesis estructural merece escalar?','¿Qué puede delegarse?|¿Qué puede delegarse preservando independencia, evidencia y responsabilidad?','¿Cómo debe construirse?|¿Cómo convertir la tesis en arquitectura ejecutable?'],''],
      ['03 / ¿Debe escalar?','Separar estructura<br>de <em>narrativa.</em>','Hacer explícita la afirmación fundamental que sostiene el negocio.',['Evidencia observada|Hipótesis|Dependencia contextual|Convención|Elección de diseño','Q Stop Criterion|Un criterio antes de que las premisas se conviertan en capital, software o infraestructura.','Q for Venture|Investigar la tesis de la startup y distinguir structural insight de narrative strength.'],'¿Existe evidencia estructural suficiente para permitir que esta premisa escale?'],
      ['04 / ¿Qué puede delegarse?','Capacidad de ejecutar.<br><em>Legitimidad para decidir.</em>','¿Debe el sistema ocupar esta función? ¿Puede verificar su propia ejecución? ¿Puede controlar el registro usado para probarla? ¿Puede juzgar conflictos en los que participa?',['Separación entre ejecución, evidencia y adjudicación.','Independencia de funciones con conflicto de interés.','Proveniencia, reconstrucción temporal y accountability.'],'Investigación: Impossible Delegation · Universal Verification Principle · The Blind Algorithm · Algorithmic Verifiability'],
      ['05 / ¿Cómo debe construirse?','De la tesis al<br><em>sistema ejecutable.</em>','Casi tres décadas en tecnología y entornos regulados, conectadas a una línea de investigación aplicada.',['Entity360|Entidades, roles, relaciones, condiciones, estados y tiempo.','MS360|Memoria organizacional, proveniencia y reconstrucción de decisiones.','QuipuDB / QuipuKM|Arquitecturas para datos, semántica, temporalidad y conocimiento.'],'Usar la implementación para probar lo que afirma la investigación.'],
      ['06 / Contribución a la aceleración','Una capacidad para<br><em>la propia aceleradora.</em>','',['Antes|Examinar la tesis|Structural Thesis Review en oportunidades de mayor complejidad.','Durante|Estructurar con el fundador|Separar hipótesis, arquitectura, delegación e implementación.','En la escala|Revisar el compromiso|Introducir un stop criterion antes de incorporar premisas a la infraestructura.'],'AI & Agentic Systems|Deep Tech|HealthTech|LegalTech / RegTech|GovTech|Research-to-Product'],
      ['Asesor de Tesis Estructural','Antes de construirlo<br>de la manera correcta,<br><em>determine si es<br>lo correcto que debe construirse.</em>','',['Benjamin Rivera Perez|Fundador, Kernel Institute|Fundador y CEO, Hyperweb Healthtech OÜ|Ejecutivo de Tecnología y Arquitecto de Sistemas, Megaweb Solutions'],'kernel.institute']
    ]
  }
};

function render(lang){
  const c=content[lang]||content.en;
  document.documentElement.lang=c.lang;
  document.title=c.title+' — Benjamin Rivera Perez';
  document.querySelector('#title').textContent=c.title;
  document.querySelector('#brand').textContent='BENJAMIN RIVERA PEREZ';
  document.querySelector('#topline').textContent=c.subtitle.toUpperCase();
  document.querySelector('#fullscreen').textContent=lang==='pt'?'Tela cheia':lang==='es'?'Pantalla completa':'Fullscreen';
  document.querySelector('#language').innerHTML=['en','pt','es'].map(x=>`<a href="${x==='en'?'index.html':x+'.html'}" class="${x===lang?'active':''}">${x.toUpperCase()}</a>`).join('');
  document.querySelector('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();
  const slides=document.querySelector('#slides'); slides.innerHTML='';
  const opening=`<section class="slide active"><p class="k">${c.proposal}</p><h1>${c.scale}</h1><p class="lead">${c.lead}</p><div class="identity">${c.role}<span>${c.founder}</span></div></section>`;
  slides.insertAdjacentHTML('beforeend',opening);
  c.slides.forEach((s)=>{let body='';const items=s[3]||[];if(items.length){body='<div class="grid">'+items.map(x=>{const p=x.split('|');return `<article class="card"><b>${p[0]}</b><h3>${p[1]||''}</h3><p>${p.slice(2).join('<br>')}</p></article>`;}).join('')+'</div>';}slides.insertAdjacentHTML('beforeend',`<section class="slide"><p class="k">${s[0]}</p><h2>${s[1]}</h2><p class="lead">${s[2]||''}</p>${body}${s[4]?`<div class="quote">${s[4]}</div>`:''}</section>`);});
  slides.insertAdjacentHTML('beforeend',`<section class="slide"><p class="k">${c.role}</p><h2>${lang==='pt'?'Antes de construir da forma correta':lang==='es'?'Antes de construirlo de la manera correcta':'Before building it the right way'},<br><em>${lang==='pt'?'determine se é a coisa certa a construir.':lang==='es'?'determine si es lo correcto que debe construirse.':'determine whether it is the right thing to build.'}</em></h2><div class="identity">Benjamin Rivera Perez<span>${c.founder}</span><span>Founder &amp; CEO, Hyperweb Healthtech OÜ</span><span>Technology Executive &amp; Systems Architect, Megaweb Solutions</span></div><p class="small"><a style="color:var(--accent)" href="https://kernel.institute">kernel.institute</a></p></section>`);
  window.showSlide(0);
}

let n=0;window.showSlide=function(i){const slides=[...document.querySelectorAll('.slide')];n=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,j)=>s.classList.toggle('active',j===n));const x=String(n+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');document.querySelector('#page').textContent=x;document.querySelector('#counter').textContent=x;document.querySelector('#prev').disabled=n===0;document.querySelector('#next').disabled=n===slides.length-1;location.hash=n+1};
document.querySelector('#prev').onclick=()=>showSlide(n-1);document.querySelector('#next').onclick=()=>showSlide(n+1);document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='PageDown')showSlide(n+1);if(e.key==='ArrowLeft'||e.key==='PageUp')showSlide(n-1);if(e.key==='Home')showSlide(0);if(e.key==='End')showSlide(99)});
